general {
    hide_cursor = false
}

background {
    monitor =
    path = screenshot     # blurs whatever's currently on screen — no wallpaper file needed
    blur_passes = 3
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgba(33ccffee)
    fail_color = rgba(ff6633ee)
    font_color = rgb(200, 200, 200)
    placeholder_text = Input password...
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 90
    position = 0, 100
    halign = center
    valign = center
}

