splash = false

wallpaper {
    monitor = DP-5
    path = ~/Pictures/Wallpapers/1314645.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-6
    path = ~/Pictures/Wallpapers/1314645.jpg
    fit_mode = cover
}
